config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :notes
  resources :tags
  resource :session
  resources :passwords, param: :token
  resources :patients
  resources :medication_products
  resources :medications
  resources :pharmacotherapies
  resources :treatments
  resources :cards do
    match :pay, via: [:patch, :post, :put], on: :member
  end
  resources :dogs
  resources :tasks do
    post :bulk_update, on: :collection
    get :summary, on: :collection
  end
  resources :responsibles, only: [:create]

  root 'home#index'

  get 'sign_up' => 'users#new', as: 'sign_up'
  get 'login' => 'session#new', as: 'login'
  post 'login' => 'session#create'
  get 'logout' => 'session#destroy', as: 'logout'

  resources :countries
  resources :payments do
    post :payments_bulk_update, on: :collection
  end
  resources :people
  resources :products
  resources :purchases do
    post :payments_bulk_update, on: :member
    post :set_installments, on: :collection
  end
  resources :quotes
  resources :session
  resources :users

  resources :galleries do
    post :find_new_galleries, on: :collection
    post :generate_photos, on: :member
  end

  resources :articles do
    resources :comments
  end

  resources :tagged_photos

  resources :photos
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :patient
  has_many :pharmacotherapies

  accepts_nested_attributes_for :pharmacotherapies, allow_destroy: true, reject_if: :all_blank

end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  before_action :set_treatment, only: %i[ show edit update destroy ]

  # GET /treatments or /treatments.json
  def index
    @treatments = Treatment.all
  end

  # GET /treatments/1 or /treatments/1.json
  def show
  end

  # GET /treatments/new
  def new
    @treatment = Treatment.new
    2.times { @treatment.pharmacotherapies.build }
    @medications = Medication.all
    @patients = Patient.all
  end

  # GET /treatments/1/edit
  def edit
  end

  # POST /treatments or /treatments.json
  def create
    @treatment = Treatment.new(treatment_params)
    @patients = Patient.all

    debugger
    respond_to do |format|
      if @treatment.save
        format.html { redirect_to treatment_url(@treatment), notice: "Treatment was successfully created." }
        format.json { render :show, status: :created, location: @treatment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /treatments/1 or /treatments/1.json
  def update
    respond_to do |format|
      if @treatment.update(treatment_params)
        format.html { redirect_to treatment_url(@treatment), notice: I18n.t('messages.saved')}
        format.json { render :show, status: :ok, location: @treatment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treatments/1 or /treatments/1.json
  def destroy
    @treatment.destroy

    respond_to do |format|
      format.html { redirect_to treatments_url, notice: "Treatment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_treatment
      @treatment = Treatment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def treatment_params
      params.require(:treatment).permit(:name, :patient_id)
    end
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/treatments/_form.html.erb
<%= form_with(model: treatment) do |form| %>
  <% if treatment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(treatment.errors.count, "error") %> prohibited this treatment from being saved:</h2>

      <ul>
        <% treatment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :patient_id, style: "display: block" %>
    <%= form.select :patient_id, options_for_select(@patients&.collect { | patient | [patient.individual.name, patient.id] }, @patient&.id), {}, {} %>
  </div>

  <fieldset>
    <legend>Tratamentos</legend>
    <%= form.fields_for :pharmacotherapies do |p_form| %>
      <div>
        <%= p_form.label :medication_id, style: "display: block" %>
        <%= p_form.select :medication_id, options_for_select(@medications&.collect { | medication | [medication.name, medication.id] }, @medication&.id), {}, {} %>
      </div>
      <div>
        <%= p_form.label :dosage_value, style: "display: block" %>
        <%= p_form.text_field :dosage_value %>
      </div>
      <div>
        <%= p_form.label :dosage_unit, style: "display: block" %>
        <%= p_form.text_field :dosage_unit %>
      </div>
      <div>
        <%= p_form.label :frequency_value, style: "display: block" %>
        <%= p_form.text_field :frequency_value %>
      </div>
      <div>
        <%= p_form.label :frequency_unit, style: "display: block" %>
        <%= p_form.text_field :frequency_unit %>
      </div>
    <% end %>
  </fieldset>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/treatments/_treatment.html.erb
<div id="<%= dom_id treatment %>">
  <p>
    <strong>Name:</strong>
    <%= treatment.name %>
  </p>

  <p>
    <strong>Patient:</strong>
    <%= treatment.patient_id %>
  </p>

</div>

app/views/treatments/edit.html.erb
<h1>Editing treatment</h1>

<%= render "form", treatment: @treatment %>

<br>

<div>
  <%= link_to "Show this treatment", @treatment %> |
  <%= link_to "Back to treatments", treatments_path %>
</div>

app/views/treatments/index.html.erb
<h1>Tratamentos</h1>

<div id="treatments">
  <% @treatments.each do |treatment| %>
    <%= render treatment %>
    <p>
      <%= link_to "Show this treatment", treatment %>
    </p>
  <% end %>
</div>

<%= link_to "New treatment", new_treatment_path %>

app/views/treatments/new.html.erb
<h1>New treatment</h1>

<%= render "form", treatment: @treatment %>

<br>

<div>
  <%= link_to "Back to treatments", treatments_path %>
</div>

app/views/treatments/show.html.erb
<%= render @treatment %>

<div>
  <%= link_to "Edit this treatment", edit_treatment_path(@treatment) %> |
  <%= link_to "Back to treatments", treatments_path %>

  <%= button_to "Destroy this treatment", @treatment, method: :delete %>
</div>