config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :notes
  resources :tags
  resource :session
  resources :passwords, param: :token
  resources :patients
  resources :medication_products
  resources :medications
  resources :pharmacotherapies
  resources :treatments
  resources :cards do
    match :pay, via: [:patch, :post, :put], on: :member
  end
  resources :dogs
  resources :tasks do
    post :bulk_update, on: :collection
    get :summary, on: :collection
  end
  resources :responsibles, only: [:create]

  root 'home#index'

  get 'sign_up' => 'users#new', as: 'sign_up'
  get 'login' => 'session#new', as: 'login'
  post 'login' => 'session#create'
  get 'logout' => 'session#destroy', as: 'logout'

  resources :countries
  resources :payments do
    post :payments_bulk_update, on: :collection
  end
  resources :people
  resources :products
  resources :purchases do
    post :payments_bulk_update, on: :member
    post :set_installments, on: :collection
  end
  resources :quotes
  resources :session
  resources :users

  resources :galleries do
    post :find_new_galleries, on: :collection
    post :generate_photos, on: :member
  end

  resources :articles do
    resources :comments
  end

  resources :tagged_photos

  resources :photos
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :purchases
  has_many :payments, through: :purchases, inverse_of: :card

  def display_name
    "#{brand} - #{name} - #{masked_number}"
  end

  def masked_number = "**** **** **** #{number.last(4)}"

  def next_due_date_from(date)
    return nil unless invoice_day.present? && due_day.present?

    due_date = Date.new(date.year, date.month, due_day)

    due_date += 1.month if date.day >= invoice_day;
    due_date += 1.month if invoice_day > due_day;
    due_date
  end

  def pay_current_month
    to_pay = payments.pending.due_this_month
    to_pay.each &:pay
    to_pay
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[ destroy edit pay show update ]

  # GET /cards or /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1 or /cards/1.json
  def show
    @total_due = @card.payments.due_this_month.pluck(:due_amount).reduce(:+)
    @total_paid = @card.payments.paid.paid_this_month.pluck(:paid_amount).reduce(:+)
    @payments = @card.payments.due_this_month
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards or /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to card_url(@card), notice: "Card was successfully created." }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to card_url(@card), notice: I18n.t('messages.saved') }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url, notice: "Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def pay
    payments_made = @card.pay_current_month
    respond_to do |format|
      if payments_made.present? && payments_made.all?
        format.html { redirect_to card_url(@card), notice: "Pagamentos registrados" }
        format.json { render :show, status: :ok }
      else
        format.html { redirect_to card_url(@card), notice: "Ocorreu um erro ao salvar" }
        format.json { render json: payments_made.map(&:errors), status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(%i( brand number name expiry_year expiry_month due_day invoice_day))
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<%
  card_class = action_name == 'index' ? 'card' : ''
%>
<div id="<%= dom_id card %>" class="<%= 'card' %>">
  <dl>
    <dt>Bandeira</dt><dd><%= card.brand %></dd>
    <dt>Número</dt><dd><%= card.number %></dd>
    <dt>Nome</dt><dd><%= card.name %></dd>
    <dt>Validade</dt><dd><%= card.expiry_year %>-<%= card.expiry_month %></dd>
    <dt>Vencimento</dt><dd><%= card.due_day %></dd>
    <dt>Melhor dia de compras</dt><dd><%= card.invoice_day ? card.invoice_day + 1 : 'não informado' %></dd>
  </dl>

  <% if action_name == 'index' %>
    <div class="actions">
      <%= link_to "Ver detalhes", card_path(id: card.id) %>
      <%= button_to "Pagar", action: "pay", id: card.id, remote: true %>
    </div>
  <% end %>
</div>

app/views/cards/_form.html.erb
<%= form_with(model: card) do |f| %>
  <% if card.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="field">
        <%= f.label :brand, 'Banndeira' %>
        <%= f.text_field :brand  %>
    </div>

    <div class="field">
        <%= f.label :number, 'Número' %>
        <%= f.text_field :number  %>
    </div>

    <div class="field">
        <%= f.label :name, 'Nome' %>
        <%= f.text_field :name  %>
    </div>

    <div class="field">
        <%= f.label :expiry_year, 'Validade (ano)' %>
        <%= f.text_field :expiry_year  %>
    </div>

    <div class="field">
        <%= f.label :expiry_month, 'Validade (mês)' %>
        <%= f.text_field :expiry_month  %>
    </div>

    <div class="field">
        <%= f.label :due_day, 'Dia de vencimento' %>
        <%= f.text_field :due_day  %>
    </div>

    <div class="field">
        <%= f.label :invoice_day, 'Dia de fechamento da fatura' %>
        <%= f.text_field :invoice_day  %>
    </div>
  </fieldset>

  <div class="actions">
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editando cartão <%= @card.brand %> <%= @card.number %> <%= @card.name %></h1>

<%= render "form", card: @card %>

<br>

<div>
  <%= link_to "Ver cartões", cards_path %>
</div>

app/views/cards/index.html.erb
<h1>Cards</h1>

<div class="actions">
  <%= link_to "Cadastrar Cartão Novo", new_card_path %>
</div>

<div id="cards">
  <%= render partial: 'card', collection: @cards%>
</div>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render "form", card: @card %>

<br>

<div>
  <%= link_to "Back to cards", cards_path %>
</div>

app/views/cards/show.html.erb
<%= render @card %>

<div class="actions">
  <%= link_to "Ver todos os cartões", cards_path %>
  <%= link_to "Editar cartão", edit_card_path(id: @card.id) %>

  <%= button_to "Pagar fatura", [:pay, @card] %>
  <%= button_to "Apagar cartão", @card, method: :delete %>
</div>

<h1>Lançamentos do mês</h1>

<%= render 'simple_table', {
  keys: ['', 'Devido', 'Pago',  'A Pagar'],
  rows: [[
    'Totais do mês',
    brl(@total_due),
    brl(@total_paid),
    brl([@total_due, @total_paid].filter(&:present?).reduce(&:-))
  ]]
}%>

<fieldset>
  <%= render 'simple_table', {
    optional: [1, 3, 5],
    keys: %w(Produto Preço Parcela Venc. Pgto  Pago),
    rows: @payments.map { |p| [
      link_to(product_short_description(p), purchase_path(p.purchase)),
      brl(p.purchase.price),
      p.paid_amount ? brl(p.paid_amount) : brl(p.due_amount),
      p.due_at&.strftime("%d"),
      p.paid_at&.strftime("%d"),
      check_box_tag("payment_ids[]", p.id, p.paid_at.present?, id: "payment_#{p.id}", disabled: true)
    ]}
  }%>
</fieldset>