config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :notes
  resources :tags
  resource :session
  resources :passwords, param: :token
  resources :patients
  resources :medication_products
  resources :medications
  resources :pharmacotherapies
  resources :treatments
  resources :cards do
    match :pay, via: [:patch, :post, :put], on: :member
  end
  resources :dogs
  resources :tasks do
    post :bulk_update, on: :collection
    get :summary, on: :collection
  end
  resources :responsibles, only: [:create]

  root 'home#index'

  get 'sign_up' => 'users#new', as: 'sign_up'
  get 'login' => 'session#new', as: 'login'
  post 'login' => 'session#create'
  get 'logout' => 'session#destroy', as: 'logout'

  resources :countries
  resources :payments do
    post :payments_bulk_update, on: :collection
  end
  resources :people
  resources :products
  resources :purchases do
    post :payments_bulk_update, on: :member
    post :set_installments, on: :collection
  end
  resources :quotes
  resources :session
  resources :users

  resources :galleries do
    post :find_new_galleries, on: :collection
    post :generate_photos, on: :member
  end

  resources :articles do
    resources :comments
  end

  resources :tagged_photos

  resources :photos
end

app/models/medication_product.rb
class MedicationProduct < ApplicationRecord
  belongs_to :medication
end

app/controllers/medication_products_controller.rb
class MedicationProductsController < ApplicationController
  before_action :set_medication_product, only: %i[ show edit update destroy ]

  # GET /medication_products or /medication_products.json
  def index
    @medication_products = MedicationProduct.all
  end

  # GET /medication_products/1 or /medication_products/1.json
  def show
  end

  # GET /medication_products/new
  def new
    @medication_product = MedicationProduct.new
  end

  # GET /medication_products/1/edit
  def edit
  end

  # POST /medication_products or /medication_products.json
  def create
    @medication_product = MedicationProduct.new(medication_product_params)

    respond_to do |format|
      if @medication_product.save
        format.html { redirect_to medication_product_url(@medication_product), notice: "Medication product was successfully created." }
        format.json { render :show, status: :created, location: @medication_product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @medication_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medication_products/1 or /medication_products/1.json
  def update
    respond_to do |format|
      if @medication_product.update(medication_product_params)
        format.html { redirect_to medication_product_url(@medication_product), notice: I18n.t('messages.saved') }
        format.json { render :show, status: :ok, location: @medication_product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @medication_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medication_products/1 or /medication_products/1.json
  def destroy
    @medication_product.destroy

    respond_to do |format|
      format.html { redirect_to medication_products_url, notice: "Medication product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medication_product
      @medication_product = MedicationProduct.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def medication_product_params
      params.require(:medication_product).permit(:name, :brand, :form, :per, :per_unit_unit, :picture, :medication_id)
    end
end

app/helpers/medication_products_helper.rb
module MedicationProductsHelper
end

app/views/medication_products/_form.html.erb
<%= form_with(model: medication_product) do |form| %>
  <% if medication_product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(medication_product.errors.count, "error") %> prohibited this medication_product from being saved:</h2>

      <ul>
        <% medication_product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :brand, style: "display: block" %>
    <%= form.text_field :brand %>
  </div>

  <div>
    <%= form.label :form, style: "display: block" %>
    <%= form.text_field :form %>
  </div>

  <div>
    <%= form.label :per, style: "display: block" %>
    <%= form.number_field :per %>
  </div>

  <div>
    <%= form.label :per_unit_unit, style: "display: block" %>
    <%= form.text_field :per_unit_unit %>
  </div>

  <div>
    <%= form.label :picture, style: "display: block" %>
    <%= form.text_field :picture %>
  </div>

  <%= form.hidden_field :medication_id  %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/medication_products/_medication_product.html.erb
<div id="<%= dom_id medication_product %>">
  <p>
    <strong>Name:</strong>
    <%= medication_product.name %>
  </p>

  <p>
    <strong>Brand:</strong>
    <%= medication_product.brand %>
  </p>

  <p>
    <strong>Form:</strong>
    <%= medication_product.form %>
  </p>

  <p>
    <strong>Per:</strong>
    <%= medication_product.per %>
  </p>

  <p>
    <strong>Per unit unit:</strong>
    <%= medication_product.per_unit_unit %>
  </p>

  <p>
    <strong>Picture:</strong>
    <%= medication_product.picture %>
  </p>

  <p>
    <strong>Medication:</strong>
    <%= medication_product.medication_id %>
  </p>

</div>

app/views/medication_products/edit.html.erb
<h1>Editing medication product</h1>

<%= render "form", medication_product: @medication_product %>

<br>

<div>
  <%= link_to "Show this medication product", @medication_product %> |
  <%= link_to "Back to medication products", medication_products_path %>
</div>

app/views/medication_products/index.html.erb
<h1>Medication products</h1>

<div id="medication_products">
  <% @medication_products.each do |medication_product| %>
    <%= render medication_product %>
    <p>
      <%= link_to "Show this medication product", medication_product %>
    </p>
  <% end %>
</div>

<%= link_to "New medication product", new_medication_product_path %>

app/views/medication_products/new.html.erb
<h1>New medication product</h1>

<%= render "form", medication_product: @medication_product %>

<br>

<div>
  <%= link_to "Back to medication products", medication_products_path %>
</div>

app/views/medication_products/show.html.erb
<%= render @medication_product %>

<div>
  <%= link_to "Edit this medication product", edit_medication_product_path(@medication_product) %> |
  <%= link_to "Back to medication products", medication_products_path %>

  <%= button_to "Destroy this medication product", @medication_product, method: :delete %>
</div>